--1. Create Database
CREATE DATABASE IF NOT EXISTS VB_ECOMMERCE_SF;

USE DATABASE VB_ECOMMERCE_SF;


--2.Create the schema
CREATE SCHEMA IF NOT EXISTS ECOMMERCE;

USE SCHEMA VB_ECOMMERCE_SF.ECOMMERCE;

--3.Create the Snowflake warehouse
CREATE WAREHOUSE IF NOT EXISTS VB_ECOMMERCE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
        
USE WAREHOUSE VB_ECOMMERCE_WH;

--4.Create our Snowflake table
CREATE OR REPLACE TABLE CUSTOMER_ORDERS
(
    ORDER_ID        INTEGER,
    CUSTOMER_ID     INTEGER,
    ORDER_DATE      DATE,
    PRODUCT_ID      INTEGER,
    QUANTITY        INTEGER,
    ORDER_AMOUNT    NUMBER(12,2),
    ORDER_STATUS    VARCHAR(20),
    MODIFIED_DATE   TIMESTAMP
);
DESC TABLE CUSTOMER_ORDERS;


--5.Insert 100 realistic records

INSERT INTO CUSTOMER_ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    PRODUCT_ID,
    QUANTITY,
    ORDER_AMOUNT,
    ORDER_STATUS,
    MODIFIED_DATE
)
SELECT
    SEQ4() + 1 AS ORDER_ID,
    UNIFORM(1, 50, RANDOM()) AS CUSTOMER_ID,
    DATEADD(
        DAY,
        -UNIFORM(1, 60, RANDOM()),
        CURRENT_DATE()
    ) AS ORDER_DATE,
    UNIFORM(1, 50, RANDOM()) AS PRODUCT_ID,
    UNIFORM(1, 5, RANDOM()) AS QUANTITY,
    ROUND(UNIFORM(500, 50000, RANDOM()) / 100, 2) AS ORDER_AMOUNT,
    CASE
        WHEN UNIFORM(1, 4, RANDOM()) = 1 THEN 'Pending'
        WHEN UNIFORM(1, 4, RANDOM()) = 2 THEN 'Confirmed'
        WHEN UNIFORM(1, 4, RANDOM()) = 3 THEN 'Shipped'
        ELSE 'Completed'
    END AS ORDER_STATUS,
    CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100));

SELECT COUNT(*) AS TOTAL_RECORDS
FROM CUSTOMER_ORDERS;


SELECT *
FROM CUSTOMER_ORDERS
ORDER BY ORDER_ID;
--6.Verify the data
SELECT
    MIN(ORDER_ID) AS MIN_ORDER_ID,
    MAX(ORDER_ID) AS MAX_ORDER_ID,
    COUNT(*) AS TOTAL_RECORDS
FROM CUSTOMER_ORDERS;
--------------------------------------------------------------------------------------
--                       Create stagging for BLOB
--------------------------------------------------------------------------------------

CREATE OR REPLACE STORAGE INTEGRATION SNOWFLAKE_AZURE_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'AZURE'
ENABLED = TRUE
AZURE_TENANT_ID = '3c9a95b3-9291-4ed2-9677-13948a6e69d0' -- from microsoft entraID
STORAGE_ALLOWED_LOCATIONS = (
    'azure://adlsvbecommercedev.blob.core.windows.net/snowflake-stage/'
);

DESC INTEGRATION SNOWFLAKE_AZURE_INTEGRATION;
--------------------------------------------------------------------------------------
--                       Stagging
--------------------------------------------------------------------------------------
USE DATABASE VB_ECOMMERCE_SF;
USE SCHEMA ECOMMERCE;

CREATE OR REPLACE STAGE STAGE_AZURE_SNOWFLAKE
URL = 'azure://adlsvbecommercedev.blob.core.windows.net/snowflake-stage/'
STORAGE_INTEGRATION = SNOWFLAKE_AZURE_INTEGRATION;

DESC STAGE STAGE_AZURE_SNOWFLAKE;

LIST @STAGE_AZURE_SNOWFLAKE;
---------------------------------------------------------------------------------------
--                         Test Snowflake → Azure stage
---------------------------------------------------------------------------------------
USE DATABASE VB_ECOMMERCE_SF;
USE SCHEMA ECOMMERCE;

COPY INTO @STAGE_AZURE_SNOWFLAKE/orders/
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS
FILE_FORMAT = (
    TYPE = PARQUET
)
OVERWRITE = TRUE;
LIST @STAGE_AZURE_SNOWFLAKE/orders/;
SHOW TABLES IN DATABASE VB_ECOMMERCE_SF;

SHOW TABLES IN SCHEMA VB_ECOMMERCE_SF.ECOMMERCE;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_ROLE();

SHOW TABLES IN DATABASE VB_ECOMMERCE_SF;
SHOW SCHEMAS IN DATABASE VB_ECOMMERCE_SF;

SELECT COUNT(*)
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS;


SELECT *
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS
LIMIT 10;

COPY INTO @STAGE_AZURE_SNOWFLAKE/orders/
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS
FILE_FORMAT = (
    TYPE = PARQUET
)
OVERWRITE = TRUE;



DESC TABLE VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS;

SELECT
    MIN(MODIFIED_DATE) AS MIN_MODIFIED_DATE,
    MAX(MODIFIED_DATE) AS MAX_MODIFIED_DATE,
    COUNT(*) AS TOTAL_RECORDS
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS;

USE DATABASE VB_ECOMMERCE_SF;
USE SCHEMA ECOMMERCE;

SELECT *
FROM CUSTOMER_ORDERS
WHERE MODIFIED_DATE > '2026-08-31 04:11:35.166';


UPDATE CUSTOMER_ORDERS
SET
    ORDER_AMOUNT = ORDER_AMOUNT + 100,
    MODIFIED_DATE = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
WHERE ORDER_ID = 1;


SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_AMOUNT,
    MODIFIED_DATE
FROM CUSTOMER_ORDERS
WHERE ORDER_ID = 1;



SELECT *
FROM CUSTOMER_ORDERS
WHERE MODIFIED_DATE > '2026-08-31 04:11:35.166';

-- inserting a new record into table to check incremental load

INSERT INTO VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    PRODUCT_ID,
    QUANTITY,
    ORDER_AMOUNT,
    ORDER_STATUS,
    MODIFIED_DATE
)
VALUES
(
    102,
    11,
    CURRENT_DATE(),
    25,
    3,
    799.99,
    'NEW',
    CURRENT_TIMESTAMP()
);

SELECT *
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS
WHERE ORDER_ID = 102;

SELECT
    MAX(MODIFIED_DATE) AS MAX_MODIFIED_DATE,
    COUNT(*) AS TOTAL_RECORDS
FROM VB_ECOMMERCE_SF.ECOMMERCE.CUSTOMER_ORDERS;